# Rose Pine theme for Alacritty
[colors.primary]
background = "#23252b"
foreground = "#F9F9F9"

[colors.normal]
black = "#3f3f3f"
red = "#fc5454"
green = "#8ae234"
yellow = "#fce94f"
blue = "#94bff3"
magenta = "#b294bb"
cyan = "#93e0e3"
white = "#dcdccc"

[colors.bright]
black = "#545454"
red = "#fc5454"
green = "#8ae234"
yellow = "#fce94f"
blue = "#94bff3"
magenta = "#b294bb"
cyan = "#93e0e3"
white = "#ffffff"

[font]
size = 11.0

[font.bold]
family = "hack"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "hack"
style = "Italic"

[font.normal]
family = "hack"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 0.8

[window.padding]
x = 15
y = 10